{ "Object corresponding to the supplied arguments does not exist", "VBOX_E_OBJECT_NOT_FOUND", 0x80BB0001 },
{ "Current virtual machine state prevents the operation", "VBOX_E_INVALID_VM_STATE", 0x80BB0002 },
{ "Virtual machine error occurred attempting the operation", "VBOX_E_VM_ERROR", 0x80BB0003 },
{ "File not accessible or erroneous file contents", "VBOX_E_FILE_ERROR", 0x80BB0004 },
{ "Runtime subsystem error", "VBOX_E_IPRT_ERROR", 0x80BB0005 },
{ "Pluggable Device Manager error", "VBOX_E_PDM_ERROR", 0x80BB0006 },
{ "Current object state prohibits operation", "VBOX_E_INVALID_OBJECT_STATE", 0x80BB0007 },
{ "Host operating system related error", "VBOX_E_HOST_ERROR", 0x80BB0008 },
{ "Requested operation is not supported", "VBOX_E_NOT_SUPPORTED", 0x80BB0009 },
{ "Invalid XML found", "VBOX_E_XML_ERROR", 0x80BB000A },
{ "Current session state prohibits operation", "VBOX_E_INVALID_SESSION_STATE", 0x80BB000B },
{ "Object being in use prohibits operation", "VBOX_E_OBJECT_IN_USE", 0x80BB000C },
{ "A provided password was incorrect", "VBOX_E_PASSWORD_INCORRECT", 0x80BB000D },
